name: JellyBook Android Builder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Workflow dependencies
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'any'
      - name: Disable Telemetry
        run: flutter --disable-telemetry
      - name: Get dependencies
        run: flutter pub get
      - name: Build debug APK
        run: flutter build apk --debug
      - name: Build debug APK (split-per-abi)
        run: flutter build apk --debug --split-per-abi
      - name: Build debug App Bundle
        run: flutter build appbundle --debug
      - name: Build release APK
        run: flutter build apk --release
      - name: Build release APK (split-per-abi)
        run: flutter build apk --release --split-per-abi
      - name: Build release App Bundle
        run: flutter build appbundle --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: build/app/outputs/apk/app-debug.apk
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debug-split-apk
          path: build/app/outputs/apk/app-debug-*.apk
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debug-bundle
          path: build/app/outputs/bundle/app-debug.aab
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/app-release.apk
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-split-apk
          path: build/app/outputs/apk/app-release-*.apk
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-bundle
          path: build/app/outputs/bundle/app-release.aab
