# Set the name of the workflow
name: Flutter-Builder



on: 
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64


      # install flutter
      - name: Flutter get
        run: flutter pub get

      # Now we build the release version for iOS
      - name: Building IPA
        run: flutter build ipa --release

      # Now we build the release version for android
      - name: Building APK
        run: flutter build apk --release

      # Collect the files (iOS)
      - name: collect ipa artifacts
        uses: actions/upload-artifact@v3
        with:
          name: JellyBook-Release-ipa
          path: build/ios/ipa/*.ipa
          if-no-files-found: error

      # Collect the files (Android)
      - name: collect APK artifacts
        uses: actions/upload-artifact@v3
        with:
          name: JellyBook-Release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
