name: JellyBook Android Builder

on: [push]

defaults:
  run:
    shell: bash

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Workflow dependencies
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'any'
      - name: Disable Telemetry
        run: flutter --disable-telemetry
      - name: Get dependencies
        run: flutter pub get
      - name: Build debug APK
        run: flutter build apk --debug
      - name: Build debug APK (split-per-abi)
        run: flutter build apk --debug --split-per-abi
      - name: Build debug App Bundle
        run: flutter build appbundle --debug
      - name: Build release APK
        run: flutter build apk --release
      - name: Build release APK (split-per-abi)
        run: flutter build apk --release --split-per-abi
      - name: Build release App Bundle
        run: flutter build appbundle --release
      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: JellyBook Debug APK
          path: JellyBook-debug.apk
      - name: Rename debug APK
        run: mv build/app/outputs/apk/app-debug.apk build/app/outputs/apk/JellyBook-debug.apk
      - name: Upload debug split APKs
        uses: actions/upload-artifact@v3
        with:
          name: JellyBook Debug Split APKs
          path: build/app/outputs/apk/JellyBook-debug-*.apk
      - name: Rename debug split APKs
        run: mv build/app/outputs/apk/app-debug-*.apk build/app/outputs/apk/JellyBook-debug-*.apk
      - name: Upload debug App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: JellyBook Debug App Bundle
          path: JellyBook-debug.aab
      - name: Rename debug App Bundle
        run: mv build/app/outputs/bundle/app-debug.aab build/app/outputs/bundle/JellyBook-debug.aab
      - name: Upload release APK
        uses: actions/upload-artifact@v3
        with:
          name: JellyBook Release APK
          path: JellyBook-release.apk
      - name: Rename release APK
        run: mv build/app/outputs/apk/app-release.apk build/app/outputs/apk/JellyBook-release.apk
      - name: Upload release split APKs
        uses: actions/upload-artifact@v3
        with:
          name: JellyBook Release Split APKs
          path: build/app/outputs/apk/JellyBook-release-*.apk
      - name: Rename release split APKs
        run: mv build/app/outputs/apk/app-release-*.apk build/app/outputs/apk/JellyBook-release-*.apk
      - name: Upload release App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: JellyBook Release App Bundle
          path: JellyBook-release.aab
