name: Auto Build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Flutter
      uses: subosito/flutter-action@v1
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 17.0.5
    - name: Build APK
      run: flutter build apk --release
      shell: bash
      env:
        FLUTTER_ROOT: ${{ runner.tool_cache }}/flutter
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: build/app/outputs/apk/release/app-release.apk
    - name: Build IPA
      run: |
        flutter build ios --release \
          --signing-certificate $SIGNING_CERTIFICATE_P12_DATA \
          --signing-certificate-password $SIGNING_CERTIFICATE_PASSWORD \
          --provisioning-profile $PROVISIONING_PROFILE_DATA
      shell: bash
      env:
        FLUTTER_ROOT: ${{ runner.tool_cache }}/flutter
        SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
        SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
        PROVISIONING_PROFILE_DATA: ${{ secrets.PROVISIONING_PROFILE_DATA }}
    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: ipa
        path: build/ios/ipa/Runner.ipa
    - name: Build APK (debug)
      run: flutter build apk
      shell: bash
      env:
        FLUTTER_ROOT: ${{ runner.tool_cache }}/flutter
    - name: Upload APK (debug)
      uses: actions/upload-artifact@v2
      with:
        name: apk (debug)
        path: build/app/outputs/apk/debug/app-debug.apk
    - name: Build IPA (debug)
      run: flutter build ios
      shell: bash
      env:
        FLUTTER_ROOT: ${{ runner.tool_cache }}/flutter
    - name: Upload IPA (debug)
      uses: actions/upload-artifact@v2
      with:
        name: ipa (debug)
        path: build/ios/ipa/Runner.ipa
